public enum ServerPackets
{
    Welcome = 1,
    SendPlayerData = 2,
    SendConnectionError = 3,
    SendRegisterError = 4,
    SendCreateGame = 5,
    CanceledLoadingGame = 6,
    SpawnMob = 7,
    UpdateMobLife = 8,
    KillMob = 9,
    UpdateLife = 10,
    UpdateMoney = 11,
    Win = 12,
    Lose = 13,
    UpdateTowerPrice = 14,
    InvokeTower = 15,
    RemoveTower = 16,
    UpdateWaveNumber = 17,
    Draw = 18,
    LoadGame = 19,
    SendLobbyCode = 20,
    SetJoinError = 21,
    MergeTower = 22,
}